name: faceid_monitor
description: Sistema de Identificação Facial - CityLabSecurity
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Layout
  bootstrap_icons: ^1.11.3
  
  # Navigation
  go_router: ^14.6.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # HTTP & API
  dio: ^5.7.0
  
  # Pagination
  infinite_scroll_pagination: ^4.1.0
  
  # Firebase (stubs para integração futura)
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.2
  
  # Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Lints
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true